version: '3.8'

services:
  web:
    environment:
      - FLASK_ENV=development
      - DEBUG=True
      - CHECK_GIT_UPDATES=false
    volumes:
      - .:/app
      - uploads_data:/app/uploads
      - logs_data:/app/logs
    command: python run.py
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
